export const questDaily = [
  { id: 1, name: "Beber 5 copos de água" },
  { id: 2, name: "Caminhar 30 minutos ao ar livre" },
  { id: 3, name: "Comer 2 porções de frutas" },
  { id: 4, name: "Fazer 10 minutos de alongamento" },
  { id: 5, name: "Dormir 8 horas" },
  { id: 6, name: "Fazer 3 séries de 15 abdominais" },
  { id: 7, name: "Meditar por 10 minutos" },
  { id: 8, name: "Evitar alimentos processados por um dia" },
  { id: 9, name: "Fazer 20 minutos de exercício de respiração" },
  { id: 10, name: "Substituir refrigerante por água ou suco natural" },
  { id: 11, name: "Comer 3 porções de vegetais" },
  { id: 12, name: "Fazer 15 minutos de ioga" },
  { id: 13, name: "Evitar açúcar refinado por um dia" },
  { id: 14, name: "Fazer 20 minutos de cardio" },
  { id: 15, name: "Tomar um chá relaxante antes de dormir" },
  { id: 16, name: "Caminhar 10.000 passos" },
  { id: 17, name: "Fazer 3 séries de 20 agachamentos" },
  { id: 18, name: "Comer um prato colorido (diversidade de alimentos)" },
  { id: 19, name: "Praticar 5 minutos de mindfulness" },
  { id: 20, name: "Ficar 1 hora sem usar telas antes de dormir" },
  { id: 21, name: "Subir escadas ao invés de usar o elevador" },
  { id: 22, name: "Fazer 10 minutos de massagem ou auto-massagem" },
  { id: 23, name: "Comer uma refeição rica em fibras" },
  { id: 24, name: "Tomar um banho relaxante" },
  { id: 25, name: "Manter uma postura correta durante o dia" },
  { id: 26, name: "Evitar cafeína após as 16h" },
  { id: 27, name: "Fazer um diário de gratidão" },
  { id: 28, name: "Tirar um cochilo de 20 minutos" },
  { id: 29, name: "Evitar alimentos fritos por um dia" },
  { id: 30, name: "Experimentar uma nova receita saudável" },
];
